reddit-clone/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :users
  resources :subs, except: [:destroy]
  resource :session
end

reddit-clone/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

reddit-clone/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :bigint           not null, primary key
#  title        :string           not null
#  description  :text             not null
#  moderator_id :bigint           not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
class Sub < ApplicationRecord
    validates :title, :description, presence: true

    belongs_to :moderator,
    foreign_key: :moderator_id,
    class_name: 'User'
end

reddit-clone/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  username        :string           not null
#  session_token   :string           not null
#  password_digest :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class User < ApplicationRecord
    validates :username, :session_token, presence: true, uniqueness: true
    validates :password_digest, presence: true
    validates :password, length: {minimum: 6}, allow_nil: true

    before_validation :ensure_session_token

    attr_reader :password

    def self.find_by_credentials(username, password)
        user = User.find_by(username: username)
        user and user.is_password?(password) ? user : nil
    end

    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password)
    end

    def is_password?(password)
        BCrypt::Password.new(self.password_digest).is_password?(password)
    end

    def reset_session_token!
        self.session_token = generate_session_token
        self.save!
        self.session_token
    end

    def ensure_session_token
        self.session_token ||= generate_session_token
    end

    private

    def generate_session_token
        token = SecureRandom::urlsafe_base64
        token = SecureRandom::urlsafe_base64 while User.exists?(session_token: token)
        token
    end 
end

reddit-clone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?
    
    def current_user
        @current_user ||= User.find_by(session_token: session[:session_token])
    end

    def require_logged_in
        redirect_to new_session_url unless logged_in?
    end

    def require_logged_out
        redirect_to users_url if logged_in?
    end

    def logged_in?
        !!current_user
    end

    def login(user)
        session[:session_token] = user.reset_session_token!
    end

    def logout!
        current_user.reset_session_token! if logged_in?
        session[:session_token] = nil
        current_user = nil
    end
end

reddit-clone/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        @user = User.new
        render :new
    end

    def create
        @user = User.find_by_credentials(params[:user][:username], params[:user][:password])

        if @user
        
            login(@user)
            redirect_to user_url(@user)
        else
            @user = User.new(username: params[:user][:username])
            flash.now[:errors] = ["Incorrect username and/or password."]
            render :new
        end
    end

    def destroy
        logout!
        redirect_to new_session_url
    end
end

reddit-clone/app/controllers/subs_controller.rb
class SubsController < ApplicationController

    def index
        @subs = Subs.all
        render :index
    end

    def show
        @sub = Sub.find_by(id: params[:id])
        render :show
    end

    def new
        @sub = Sub.new
        render :new
    end

    def create
        @sub = current_user.subs.new(sub_params)
        if @sub.save
            flash[:notice] = ['Successfully created!']
            redirect_to sub_url(@sub)
        else
            flash.now[:errors] = @sub.errors.full_messages
            render :new
        end
    end

    def edit
        @sub = Sub.find_by(id: params[:id])
        render :edit
    end

    def update
        @sub = Sub.find_by(id: params[:id])
        if @sub.update(sub_params)
            flash[:notice] = ['Successfully updated']
            redirect_to sub_url(@sub)
        else
            flash.now[:errors] = @sub.errors.full_messages
            render :new
        end
    end

    private

    def sub_params
        params.require(:sub).permit(:title, :description)
    end
end

reddit-clone/app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index
        @user = User.all
        render :index
    end

    def show
        @user = User.find_by(id: params[:id])
        render :show
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            login(@user)
            redirect_to user_url(@user)
        else
            flash.now[:errors] = @user.errors.full_messages
            render :new
        end
    end

    private

    def user_params
        params.require(:user).permit(:username, :password)
    end

end

reddit-clone/app/helpers/application_helper.rb
module ApplicationHelper
end

reddit-clone/app/helpers/sessions_helper.rb
module SessionsHelper
end

reddit-clone/app/helpers/sub_helper.rb
module SubHelper
end

reddit-clone/app/helpers/users_helper.rb
module UsersHelper
end

reddit-clone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>RedditClone</title>
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

        <%= stylesheet_link_tag "application" %>
    </head>

    <body>
        <% if flash[:notice] %>
            <% flash[:notice].each do |notice| %>
                <p><%= notice %></p>
            <% end %>
        <% end %>

        <% if logged_in? %>
            <h2>Welcome, <%= current_user.username %></h2>

            <form action="<%= session_url %>" method="POST">
                <input type="hidden" name="_method" value="DELETE">
                <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
                <button>Sign Out</button>
            </form>
        <% else %>
            <a href="<%= new_session_url %>">Log In</a>
            <a href="<%= new_user_url %>">Sign Up</a>
        <% end %>

        <%= yield %>
        
        <% if flash[:errors] %>
            <% flash[:errors].each do |error| %>
                <p><%= error %></p>
            <% end %>
        <% end %>
    </body>
</html>

reddit-clone/app/views/sub/edit.html.erb
<h2>Update Sub</h2>

<form action="<%= sub_url(@sub) %>" method="POST">
    <input type="hidden" name="_method" value="PATCH">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <label>Title: 
        <input type="text" name="sub[title]" value="<%= @sub.title %>">    
    </label>

    <label>Description: 
        <textarea name="sub[description]"><%= @sub.description %></textarea>   
    </label>
    
    <button>Update Sub</button>
</form>

reddit-clone/app/views/sub/index.html.erb
<h2>All Subs</h2>

<% @subs.each do |sub| %>
    <a href="<%= sub_url(sub) %>"><%= sub.title %></a>
<% end %>

reddit-clone/app/views/sub/show.html.erb
<h2><%= @sub.title %></h2>
<p>Description: <%= @sub.description %></p>

reddit-clone/app/views/users/new.html.erb
<h2>Sign Up</h2>

<form action=" <%= users_url %>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <label>Username: 
        <input type="text" name="user[username]" value="<%= @user.username %>">
    </label>

    <label>Password: 
        <input type="password" name="user[password]">
    </label>

    <button>Sign Up</button>
</form>

reddit-clone/app/views/users/show.html.erb
<h1>Welcome, <%= @user.username %></h1>